- name: Idempotent command
  ignore_errors: yes
  hosts: alma2
  tasks:
    - command: useradd joan
      register: added_user
    - name: rc 9 is ok
      assert:
        that:
        - added_user.rc == 9
        success_msg: User already exists

    - debug:
        msg: cotniuning her
